version: '2.1'

volumes:
  postgres_data_dev: {}

services:
  postgres:
    image: postgres:9.6
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=concepttoclinic

  interface:
    build:
      context: .
      dockerfile: ./compose/interface/Dockerfile-dev
    command: /start-dev.sh
    depends_on:
      - postgres
      - prediction
    environment:
      - POSTGRES_USER=concepttoclinic
      - USE_DOCKER=yes
      - SECRET_KEY=notverysecret
      - DEBUG=True
      - DJANGO_SETTINGS_MODULE=config.settings.local
    volumes:
      - ./interface/:/app
      - ./tests/assets/test_image_data/small:/images
      - ./.git/logs/HEAD:/HEAD
      - ./prediction/src/algorithms/classify/assets/:/classify_models
    ports:
      - "8000:8000"

  prediction:
    build:
      context: .
      dockerfile: ./compose/prediction/Dockerfile-dev
    command: flask run --host=0.0.0.0 --port=8013
    environment:
      - FLASK_DEBUG=1
      - FLASK_APP=src/factory.py
    volumes:
      - ./prediction/:/app
      - ./tests/assets/test_image_data/small:/images
      - ./prediction/src/algorithms/classify/assets/:/classify_models
    ports:
      - "8001:8001"

  # compile_docs:
  #     restart: always
  #     build:
  #       context: .
  #       dockerfile: ./compose/prediction/Dockerfile-dev
  #     volumes:
  #       - ./:/app
  #     command: make -C /app/docs html

  # documentation:
  #   build:
  #     context: .
  #     dockerfile: ./compose/prediction/Dockerfile-dev
  #   depends_on:
  #     - compile_docs
  #   working_dir: /app/docs/_build/html
  #   volumes:
  #     - ./docs/_build/html:/app/docs/_build/html
  #     - ./:/app
  #   command: python -m http.server
  #   ports:
  #     - "8002:8000"
